export const DATA = [
  {
    id: 'Jan',
    title: 'January',
    days: [
      {id: 36, date: '1', day: 'Fri'},
      {id: 37, date: '2', day: 'Sat'},
      {id: 38, date: '3', day: 'Sun'},
      {id: 39, date: '4', day: 'Mon'},
      {id: 40, date: '5', day: 'Tue'},
      {id: 41, date: '6', day: 'Wed'},
      {id: 42, date: '7', day: 'Thu'},
      {id: 43, date: '8', day: 'Fri'},
      {id: 44, date: '9', day: 'Sat'},
      {id: 45, date: '10', day: 'Sun'},
      {id: 46, date: '11', day: 'Mon'},
      {id: 47, date: '12', day: 'Tue'},
      {id: 48, date: '13', day: 'Wed'},
      {id: 49, date: '14', day: 'Thu'},
      {id: 50, date: '15', day: 'Fri'},
      {id: 51, date: '16', day: 'Sat'},
      {id: 52, date: '17', day: 'Sun'},
      {id: 53, date: '18', day: 'Mon'},
      {id: 54, date: '19', day: 'Tue'},
      {id: 55, date: '20', day: 'Wed'},
      {id: 56, date: '21', day: 'Thu'},
      {id: 57, date: '22', day: 'Fri'},
      {id: 58, date: '23', day: 'Sat'},
      {id: 59, date: '24', day: 'Sun'},
      {id: 60, date: '25', day: 'Mon'},
      {id: 61, date: '26', day: 'Tue'},
      {id: 62, date: '27', day: 'Wed'},
      {id: 63, date: '28', day: 'Thu'},
      {id: 64, date: '29', day: 'Fri'},
      {id: 65, date: '30', day: 'Sat'},
      {id: 66, date: '31', day: 'Sun'},
    ],
  },
  {
    id: 'Feb',
    title: 'February',
    days: [
      {id: 39, date: '1', day: 'Mon'},
      {id: 40, date: '2', day: 'Tue'},
      {id: 41, date: '3', day: 'Wed'},
      {id: 42, date: '4', day: 'Thu'},
      {id: 43, date: '5', day: 'Fri'},
      {id: 44, date: '6', day: 'Sat'},
      {id: 45, date: '7', day: 'Sun'},
      {id: 46, date: '8', day: 'Mon'},
      {id: 47, date: '9', day: 'Tue'},
      {id: 48, date: '10', day: 'Wed'},
      {id: 49, date: '11', day: 'Thu'},
      {id: 50, date: '12', day: 'Fri'},
      {id: 51, date: '13', day: 'Sat'},
      {id: 52, date: '14', day: 'Sun'},
      {id: 53, date: '15', day: 'Mon'},
      {id: 54, date: '16', day: 'Tue'},
      {id: 55, date: '17', day: 'Wed'},
      {id: 56, date: '18', day: 'Thu'},
      {id: 57, date: '19', day: 'Fri'},
      {id: 58, date: '20', day: 'Sat'},
      {id: 59, date: '21', day: 'Sun'},
      {id: 60, date: '22', day: 'Mon'},
      {id: 61, date: '23', day: 'Tue'},
      {id: 62, date: '24', day: 'Wed'},
      {id: 63, date: '25', day: 'Thu'},
      {id: 64, date: '26', day: 'Fri'},
      {id: 65, date: '27', day: 'Sat'},
      {id: 66, date: '28', day: 'Sun'},
    ],
  },
  {
    id: 'March',
    title: 'March',
    days: [
      {id: 32, date: '1', day: 'Mon'},
      {id: 33, date: '2', day: 'Tue'},
      {id: 34, date: '3', day: 'Wed'},
      {id: 35, date: '4', day: 'Thu'},
      {id: 36, date: '5', day: 'Fri'},
      {id: 37, date: '6', day: 'Sat'},
      {id: 38, date: '7', day: 'Sun'},
      {id: 39, date: '8', day: 'Mon'},
      {id: 40, date: '9', day: 'Tue'},
      {id: 41, date: '10', day: 'Wed'},
      {id: 42, date: '11', day: 'Thu'},
      {id: 43, date: '12', day: 'Fri'},
      {id: 44, date: '13', day: 'Sat'},
      {id: 45, date: '14', day: 'Sun'},
      {id: 46, date: '15', day: 'Mon'},
      {id: 47, date: '16', day: 'Tue'},
      {id: 48, date: '17', day: 'Wed'},
      {id: 49, date: '18', day: 'Thu'},
      {id: 50, date: '19', day: 'Fri'},
      {id: 51, date: '20', day: 'Sat'},
      {id: 52, date: '21', day: 'Sun'},
      {id: 53, date: '22', day: 'Mon'},
      {id: 54, date: '23', day: 'Tue'},
      {id: 55, date: '24', day: 'Wed'},
      {id: 56, date: '25', day: 'Thu'},
      {id: 57, date: '26', day: 'Fri'},
      {id: 58, date: '27', day: 'Sat'},
      {id: 59, date: '28', day: 'Sun'},
      {id: 60, date: '29', day: 'Mon'},
      {id: 61, date: '30', day: 'Tue'},
      {id: 62, date: '31', day: 'Wed'},
    ],
  },
  {
    id: 'April',
    title: 'April',
    days: [
      {
        id: 35,
        date: '1',
        day: 'Thu',
        data: [
          {
            heading: 'Mobile App Design',
            peeps: 'Mike and Anita',
            time: '9:00 AM - 10:00AM',
            image: 'profile.png',
          },
          {
            heading: 'Software Testing',
            peeps: 'Anita and David',
            time: '10:00 AM - 11:20AM',
            image: 'profile.png',
          },
          {
            heading: 'Web Development',
            peeps: 'Mike and Anita',
            time: '1:00 PM - 2:00PM',
            image: 'profile.png',
          },
        ],
      },
      {
        id: 36,
        date: '2',
        day: 'Fri',
        data: [
          {
            heading: 'Mobile App Development',
            peeps: 'Peter and Anita',
            time: '9:00 AM - 9:45AM',
            image: 'profile.png',
          },
          {
            heading: 'Web Development',
            peeps: 'Anita and John',
            time: '11:00 AM - 12:20AM',
            image: 'profile.png',
          },
          {
            heading: 'Software Testing',
            peeps: 'Alice and Anita',
            time: '3:00 PM - 4:00PM',
            image: 'profile.png',
          },
        ],
      },
      {id: 37, date: '3', day: 'Sat'},
      {id: 38, date: '4', day: 'Sun'},
      {id: 39, date: '5', day: 'Mon'},
      {id: 40, date: '6', day: 'Tue'},
      {id: 41, date: '7', day: 'Wed'},
      {id: 42, date: '8', day: 'Thu'},
      {id: 43, date: '9', day: 'Fri'},
      {id: 44, date: '10', day: 'Sat'},
      {id: 45, date: '11', day: 'Sun'},
      {id: 46, date: '12', day: 'Mon'},
      {id: 47, date: '13', day: 'Tue'},
      {id: 48, date: '14', day: 'Wed'},
      {id: 49, date: '15', day: 'Thu'},
      {id: 50, date: '16', day: 'Fri'},
      {id: 51, date: '17', day: 'Sat'},
      {id: 52, date: '18', day: 'Sun'},
      {id: 53, date: '19', day: 'Mon'},
      {id: 54, date: '20', day: 'Tue'},
      {id: 55, date: '21', day: 'Wed'},
      {id: 56, date: '22', day: 'Thu'},
      {id: 57, date: '23', day: 'Fri'},
      {id: 58, date: '24', day: 'Sat'},
      {id: 59, date: '25', day: 'Sun'},
      {id: 60, date: '26', day: 'Mon'},
      {id: 61, date: '27', day: 'Tue'},
      {id: 62, date: '28', day: 'Wed'},
      {id: 63, date: '29', day: 'Thu'},
      {id: 64, date: '30', day: 'Fri'},
    ],
  },
  {
    id: 'May',
    title: 'May',
    days: [
      {id: 34, date: '1', day: 'Sat'},
      {id: 35, date: '2', day: 'Sun'},
      {id: 36, date: '3', day: 'Mon'},
      {id: 37, date: '4', day: 'Tue'},
      {id: 38, date: '5', day: 'Wed'},
      {id: 39, date: '6', day: 'Thu'},
      {id: 40, date: '7', day: 'Fri'},
      {id: 41, date: '8', day: 'Sat'},
      {id: 42, date: '9', day: 'Sun'},
      {id: 43, date: '10', day: 'Mon'},
      {id: 44, date: '11', day: 'Tue'},
      {id: 45, date: '12', day: 'Wed'},
      {id: 46, date: '13', day: 'Thu'},
      {id: 47, date: '14', day: 'Fri'},
      {id: 48, date: '15', day: 'Sat'},
      {id: 49, date: '16', day: 'Sun'},
      {id: 50, date: '17', day: 'Mon'},
      {id: 51, date: '18', day: 'Tue'},
      {id: 52, date: '19', day: 'Wed'},
      {id: 53, date: '20', day: 'Thu'},
      {id: 54, date: '21', day: 'Fri'},
      {id: 55, date: '22', day: 'Sat'},
      {id: 56, date: '23', day: 'Sun'},
      {id: 57, date: '24', day: 'Mon'},
      {id: 58, date: '25', day: 'Tue'},
      {id: 59, date: '26', day: 'Wed'},
      {id: 60, date: '27', day: 'Thu'},
      {id: 61, date: '28', day: 'Fri'},
      {id: 62, date: '29', day: 'Sat'},
      {id: 63, date: '30', day: 'Sun'},
      {id: 64, date: '31', day: 'Mon'},
    ],
  },
  {
    id: 'June',
    title: 'June',
    days: [
      {id: 33, date: '1', day: 'Tue'},
      {id: 34, date: '2', day: 'Wed'},
      {id: 35, date: '3', day: 'Thu'},
      {id: 36, date: '4', day: 'Fri'},
      {id: 37, date: '5', day: 'Sat'},
      {id: 38, date: '6', day: 'Sun'},
      {id: 39, date: '7', day: 'Mon'},
      {id: 40, date: '8', day: 'Tue'},
      {id: 41, date: '9', day: 'Wed'},
      {id: 42, date: '10', day: 'Thu'},
      {id: 43, date: '11', day: 'Fri'},
      {id: 44, date: '12', day: 'Sat'},
      {id: 45, date: '13', day: 'Sun'},
      {id: 46, date: '14', day: 'Mon'},
      {id: 47, date: '15', day: 'Tue'},
      {id: 48, date: '16', day: 'Wed'},
      {id: 49, date: '17', day: 'Thu'},
      {id: 50, date: '18', day: 'Fri'},
      {id: 51, date: '19', day: 'Sat'},
      {id: 52, date: '20', day: 'Sun'},
      {id: 53, date: '21', day: 'Mon'},
      {id: 54, date: '22', day: 'Tue'},
      {id: 55, date: '23', day: 'Wed'},
      {id: 56, date: '24', day: 'Thu'},
      {id: 57, date: '25', day: 'Fri'},
      {id: 58, date: '26', day: 'Sat'},
      {id: 59, date: '27', day: 'Sun'},
      {id: 60, date: '28', day: 'Mon'},
      {id: 61, date: '29', day: 'Tue'},
      {id: 62, date: '30', day: 'Wed'},
    ],
  },
  {
    id: 'July',
    title: 'July',
    days: [
      {id: 35, date: '1', day: 'Thu'},
      {id: 36, date: '2', day: 'Fri'},
      {id: 37, date: '3', day: 'Sat'},
      {id: 38, date: '4', day: 'Sun'},
      {id: 39, date: '5', day: 'Mon'},
      {id: 40, date: '6', day: 'Tue'},
      {id: 41, date: '7', day: 'Wed'},
      {id: 42, date: '8', day: 'Thu'},
      {id: 43, date: '9', day: 'Fri'},
      {id: 44, date: '10', day: 'Sat'},
      {id: 45, date: '11', day: 'Sun'},
      {id: 46, date: '12', day: 'Mon'},
      {id: 47, date: '13', day: 'Tue'},
      {id: 48, date: '14', day: 'Wed'},
      {id: 49, date: '15', day: 'Thu'},
      {id: 50, date: '16', day: 'Fri'},
      {id: 51, date: '17', day: 'Sat'},
      {id: 52, date: '18', day: 'Sun'},
      {id: 53, date: '19', day: 'Mon'},
      {id: 54, date: '20', day: 'Tue'},
      {id: 55, date: '21', day: 'Wed'},
      {id: 56, date: '22', day: 'Thu'},
      {id: 57, date: '23', day: 'Fri'},
      {id: 58, date: '24', day: 'Sat'},
      {id: 59, date: '25', day: 'Sun'},
      {id: 60, date: '26', day: 'Mon'},
      {id: 61, date: '27', day: 'Tue'},
      {id: 62, date: '28', day: 'Wed'},
      {id: 63, date: '29', day: 'Thu'},
      {id: 64, date: '30', day: 'Fri'},
      {id: 65, date: '31', day: 'Sat'},
    ],
  },
  {
    id: 'Aug',
    title: 'August',
    days: [
      {id: 38, date: '1', day: 'Sun'},
      {id: 39, date: '2', day: 'Mon'},
      {id: 40, date: '3', day: 'Tue'},
      {id: 41, date: '4', day: 'Wed'},
      {id: 42, date: '5', day: 'Thu'},
      {id: 43, date: '6', day: 'Fri'},
      {id: 44, date: '7', day: 'Sat'},
      {id: 45, date: '8', day: 'Sun'},
      {id: 46, date: '9', day: 'Mon'},
      {id: 47, date: '10', day: 'Tue'},
      {id: 48, date: '11', day: 'Wed'},
      {id: 49, date: '12', day: 'Thu'},
      {id: 50, date: '13', day: 'Fri'},
      {id: 51, date: '14', day: 'Sat'},
      {id: 52, date: '15', day: 'Sun'},
      {id: 53, date: '16', day: 'Mon'},
      {id: 54, date: '17', day: 'Tue'},
      {id: 55, date: '18', day: 'Wed'},
      {id: 56, date: '19', day: 'Thu'},
      {id: 57, date: '20', day: 'Fri'},
      {id: 58, date: '21', day: 'Sat'},
      {id: 59, date: '22', day: 'Sun'},
      {id: 60, date: '23', day: 'Mon'},
      {id: 61, date: '24', day: 'Tue'},
      {id: 62, date: '25', day: 'Wed'},
      {id: 63, date: '26', day: 'Thu'},
      {id: 64, date: '27', day: 'Fri'},
      {id: 65, date: '28', day: 'Sat'},
      {id: 66, date: '29', day: 'Sun'},
      {id: 67, date: '30', day: 'Mon'},
      {id: 68, date: '31', day: 'Tue'},
    ],
  },
  {
    id: 'Sep',
    title: 'September',
    days: [
      {id: 34, date: '1', day: 'Wed'},
      {id: 35, date: '2', day: 'Thu'},
      {id: 36, date: '3', day: 'Fri'},
      {id: 37, date: '4', day: 'Sat'},
      {id: 38, date: '5', day: 'Sun'},
      {id: 39, date: '6', day: 'Mon'},
      {id: 40, date: '7', day: 'Tue'},
      {id: 41, date: '8', day: 'Wed'},
      {id: 42, date: '9', day: 'Thu'},
      {id: 43, date: '10', day: 'Fri'},
      {id: 44, date: '11', day: 'Sat'},
      {id: 45, date: '12', day: 'Sun'},
      {id: 46, date: '13', day: 'Mon'},
      {id: 47, date: '14', day: 'Tue'},
      {id: 48, date: '15', day: 'Wed'},
      {id: 49, date: '16', day: 'Thu'},
      {id: 50, date: '17', day: 'Fri'},
      {id: 51, date: '18', day: 'Sat'},
      {id: 52, date: '19', day: 'Sun'},
      {id: 53, date: '20', day: 'Mon'},
      {id: 54, date: '21', day: 'Tue'},
      {id: 55, date: '22', day: 'Wed'},
      {id: 56, date: '23', day: 'Thu'},
      {id: 57, date: '24', day: 'Fri'},
      {id: 58, date: '25', day: 'Sat'},
      {id: 59, date: '26', day: 'Sun'},
      {id: 60, date: '27', day: 'Mon'},
      {id: 61, date: '28', day: 'Tue'},
      {id: 62, date: '29', day: 'Wed'},
      {id: 63, date: '30', day: 'Thu'},
    ],
  },
  {
    id: 'Oct',
    title: 'October',
    days: [
      {id: 36, date: '1', day: 'Fri'},
      {id: 37, date: '2', day: 'Sat'},
      {id: 38, date: '3', day: 'Sun'},
      {id: 39, date: '4', day: 'Mon'},
      {id: 40, date: '5', day: 'Tue'},
      {id: 41, date: '6', day: 'Wed'},
      {id: 42, date: '7', day: 'Thu'},
      {id: 43, date: '8', day: 'Fri'},
      {id: 44, date: '9', day: 'Sat'},
      {id: 45, date: '10', day: 'Sun'},
      {id: 46, date: '11', day: 'Mon'},
      {id: 47, date: '12', day: 'Tue'},
      {id: 48, date: '13', day: 'Wed'},
      {id: 49, date: '14', day: 'Thu'},
      {id: 50, date: '15', day: 'Fri'},
      {id: 51, date: '16', day: 'Sat'},
      {id: 52, date: '17', day: 'Sun'},
      {id: 53, date: '18', day: 'Mon'},
      {id: 54, date: '19', day: 'Tue'},
      {id: 55, date: '20', day: 'Wed'},
      {id: 56, date: '21', day: 'Thu'},
      {id: 57, date: '22', day: 'Fri'},
      {id: 58, date: '23', day: 'Sat'},
      {id: 59, date: '24', day: 'Sun'},
      {id: 60, date: '25', day: 'Mon'},
      {id: 61, date: '26', day: 'Tue'},
      {id: 62, date: '27', day: 'Wed'},
      {id: 63, date: '28', day: 'Thu'},
      {id: 64, date: '29', day: 'Fri'},
      {id: 65, date: '30', day: 'Sat'},
      {id: 66, date: '31', day: 'Sun'},
    ],
  },
  {
    id: 'Nov',
    title: 'November',
    days: [
      {id: 39, date: '1', day: 'Mon'},
      {id: 40, date: '2', day: 'Tue'},
      {id: 41, date: '3', day: 'Wed'},
      {id: 42, date: '4', day: 'Thu'},
      {id: 43, date: '5', day: 'Fri'},
      {id: 44, date: '6', day: 'Sat'},
      {id: 45, date: '7', day: 'Sun'},
      {id: 46, date: '8', day: 'Mon'},
      {id: 47, date: '9', day: 'Tue'},
      {id: 48, date: '10', day: 'Wed'},
      {id: 49, date: '11', day: 'Thu'},
      {id: 50, date: '12', day: 'Fri'},
      {id: 51, date: '13', day: 'Sat'},
      {id: 52, date: '14', day: 'Sun'},
      {id: 53, date: '15', day: 'Mon'},
      {id: 54, date: '16', day: 'Tue'},
      {id: 55, date: '17', day: 'Wed'},
      {id: 56, date: '18', day: 'Thu'},
      {id: 57, date: '19', day: 'Fri'},
      {id: 58, date: '20', day: 'Sat'},
      {id: 59, date: '21', day: 'Sun'},
      {id: 60, date: '22', day: 'Mon'},
      {id: 61, date: '23', day: 'Tue'},
      {id: 62, date: '24', day: 'Wed'},
      {id: 63, date: '25', day: 'Thu'},
      {id: 64, date: '26', day: 'Fri'},
      {id: 66, date: '27', day: 'Sat'},
      {id: 67, date: '28', day: 'Sun'},
      {id: 68, date: '29', day: 'Mon'},
      {id: 69, date: '30', day: 'Tue'},
    ],
  },
  {
    id: 'Dec',
    title: 'December',
    days: [
      {id: 34, date: '1', day: 'Wed'},
      {id: 35, date: '2', day: 'Thu'},
      {id: 36, date: '3', day: 'Fri'},
      {id: 37, date: '4', day: 'Sat'},
      {id: 38, date: '5', day: 'Sun'},
      {id: 39, date: '6', day: 'Mon'},
      {id: 40, date: '7', day: 'Tue'},
      {id: 41, date: '8', day: 'Wed'},
      {id: 42, date: '9', day: 'Thu'},
      {id: 43, date: '10', day: 'Fri'},
      {id: 44, date: '11', day: 'Sat'},
      {id: 45, date: '12', day: 'Sun'},
      {id: 46, date: '13', day: 'Mon'},
      {id: 47, date: '14', day: 'Tue'},
      {id: 48, date: '15', day: 'Wed'},
      {id: 49, date: '16', day: 'Thu'},
      {id: 50, date: '17', day: 'Fri'},
      {id: 51, date: '18', day: 'Sat'},
      {id: 52, date: '19', day: 'Sun'},
      {id: 53, date: '20', day: 'Mon'},
      {id: 54, date: '21', day: 'Tue'},
      {id: 55, date: '22', day: 'Wed'},
      {id: 56, date: '23', day: 'Thu'},
      {id: 57, date: '24', day: 'Fri'},
      {id: 58, date: '25', day: 'Sat'},
      {id: 59, date: '26', day: 'Sun'},
      {id: 60, date: '27', day: 'Mon'},
      {id: 61, date: '28', day: 'Tue'},
      {id: 62, date: '29', day: 'Wed'},
      {id: 63, date: '30', day: 'Thu'},
      {id: 64, date: '31', day: 'Fri'},
    ],
  },
];
